version: '3.8' 
services:
  postgres:
    image: postgres:15
    container_name: AnoNote_postgres
    environment:
      POSTGRES_USER: ano_user
      POSTGRES_PASSWORD: d8ky654n # Пароль
      POSTGRES_DB: anonote_db     # Имя базы
    ports:
      - "5439:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: